export const ON_CHANGE_VALUE = 'ON_CHANGE_VALUE'
export const DELETE_CERTAIN_PORTFOLIO_ITEM = 'DELETE_CERTAIN_PORTFOLIO_ITEM'
export const NEW_ADDITION_TO_CMS_CONTENT = 'NEW_ADDITION_TO_CMS_CONTENT'
export const FETCHED_CMS_PORTFOLIO_DATA = 'FETCHED_CMS_PORTFOLIO_DATA'